Controllers/ThanhToanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models.Entities;
using WebApplication1.Models.ViewModels;
using WebApplication1.Repositories;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class ThanhToanController : Controller
    {
        private readonly IGoiDichVuRepository _goiRepo;
        private readonly IThanhToanRepository _thanhToanRepo;
        private readonly IThanhToanService _thanhToanService;
        private readonly IDangTinRepository _baiDangRepo;
        private readonly UserManager<TaiKhoan> _userManager;

        public ThanhToanController(
           IGoiDichVuRepository goiRepo,
           IThanhToanRepository thanhToanRepo,
           IThanhToanService thanhToanService,
           IDangTinRepository baiDangRepo,
           UserManager<TaiKhoan> userManager)
        {
            _goiRepo = goiRepo;
            _thanhToanRepo = thanhToanRepo;
            _thanhToanService = thanhToanService;
            _baiDangRepo = baiDangRepo;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ChonGoi(int baiDangId)
        {
            var gois = _goiRepo.GetAll();
            var vm = new GoiViewModel
            {
                BaiDangId = baiDangId,
                GoiDichVus = gois
            };
            return View(vm);
        }

        public IActionResult XacNhan(int goiId, int baiDangId)
        {
            var goi = _goiRepo.GetById(goiId);
            var vm = new XacNhanTTViewModel
            {
                BaiDangId = baiDangId,
                GoiDichVu = goi
            };
            if (goi == null)
            {
                TempData["Tittle"] = "Vui lòng chọn lại gói";
                TempData["ErrorMessage"] = "Gói dịch vụ không tồn tại.";
                return RedirectToAction("ChonGoi", new { BaiDangId = baiDangId });
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> ThanhToanGoi(int BaiDangId, int GoiId)
        {
            var user = await _userManager.GetUserAsync(User);
            var goi = _goiRepo.GetById(GoiId);

            var thanhToan = new ThanhToan
            {
                TaiKhoanId = user.Id,
                GoiDichVuId = GoiId,
                NgayThanhToan = DateTime.Now,
                BaiDangId = BaiDangId,
                IsDuyet = false,
            };

            _thanhToanRepo.Them(thanhToan);
            var baiDang = await _baiDangRepo.GetBaiDangById(BaiDangId);
            if (baiDang != null)
            {
                baiDang.sTrangThaiGD = "Chờ duyệt"; // bạn nên dùng enum hoặc hằng số nếu có
                await _baiDangRepo.UpdateDangTin(baiDang);
                TempData["Tittle"] = "Thanh toán của bạn đang chờ duyệt";
                TempData["SuccessMessage"] = "Thanh toán thành công!";
                return RedirectToAction("Index", "baiDang");
            }
            else
            {
                TempData["Tittle"] = "Vui lòng thanh toán lại.";
                TempData["ErrorMessage"] = "Thanh toán thất bại !";
                return View();
            }
                // Đẩy bài đăng lên đầu (cập nhật NgayDang)
                //_baiDangRepo.CapNhatThoiGianDang(BaiDangId, DateTime.Now.AddDays(goi.SoNgayHieuLuc));

                return RedirectToAction("Index", "baiDang");
        }

        public async Task<IActionResult> DonHang()
        {
            var userId = _userManager.GetUserId(User);
            var model = await _thanhToanService.GetLichSuThanhToanAsync(userId);
            return View(model);
        }

        /*[Authorize(Roles = "Admin")]
        public async Task<IActionResult> LichSuThanhToanAdmin()
        {
            var model = await _thanhToanService.GetAllLichSuThanhToanAsync();
            return View(model);
        }*/



    }
}

Controllers/baiDangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Models.Entities;
using WebApplication1.Repositories;
using WebApplication1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Globalization;
using System.Text;

namespace WebApplication1.Controllers
{
    public class baiDangController : Controller
    {
        private readonly ILogger<baiDangController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly UserManager<TaiKhoan> _userManager;
        private readonly SignInManager<TaiKhoan> _signInManager;
        private readonly IDangTinService _dangTinService;
        private readonly IDangTinRepository _dangTinRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly IUngTuyenService _IUngTuyenService;
        private readonly ICustomEmailSender _emailSender;
        private readonly IUngTuyenRepository _ungTuyenRepo;

        public baiDangController(
            ILogger<baiDangController> logger,
            IWebHostEnvironment webHostEnvironment,
            ApplicationDbContext context,
            IConfiguration configuration,
            UserManager<TaiKhoan> userManager,
            SignInManager<TaiKhoan> signInManager,
            IDangTinService dangTinService,
            IAccountRepository accountRepository,
            IUngTuyenService IUngTuyenService,
            IDangTinRepository dangTinRepository,
            ICustomEmailSender emailSender,
            IUngTuyenRepository ungTuyenRepo
            )
        {
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _configuration = configuration;
            _userManager = userManager;
            _signInManager = signInManager;
            _dangTinService = dangTinService;
            _dangTinRepository = dangTinRepository;
            _accountRepository = accountRepository;
            _IUngTuyenService = IUngTuyenService;
            _emailSender = emailSender;
            _ungTuyenRepo = ungTuyenRepo;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult DangTin()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> DangTin(DangTinViewModel model)
        {
           
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            _logger.LogInformation("DangTin action called with model: {@Model}", model);


            if (string.IsNullOrEmpty(model.sTieuDe) || string.IsNullOrEmpty(model.sDiaDiem) || model.fMucLuong <= 0 || string.IsNullOrEmpty(model.sMoTa) || string.IsNullOrEmpty(model.sYCau) || string.IsNullOrEmpty(model.sBangCap) || string.IsNullOrEmpty(model.sGioiTinh) || string.IsNullOrEmpty(model.sKinhNghiem) || string.IsNullOrEmpty(model.sMonday) || string.IsNullOrEmpty(model.sTuoi))
            {
                ModelState.AddModelError("", "Vui lòng điền đầy đủ thông tin!");
                return View(model);
            }

            //var dangTin = new BaiDang();

          //  bool isExist = await _dangTinService.DangTinExistsByTitleAsync(model.sTieuDe);
            //if (isExist)
           // {
            //    ModelState.AddModelError("", "Tiêu đề đã tồn tại!");
           //     return View(model);
           // }
            /*  dangTin.sMonday = model.sMonday;
              dangTin.sYCau = model.sYCau;
              dangTin.sGioiTinh = model.sGioiTinh;
              dangTin.sTuoi = model.sTuoi;
              dangTin.sKinhNghiem = model.sKinhNghiem;
              dangTin.sBangCap = model.sBangCap;
              dangTin.sTieuDe = model.sTieuDe;
              dangTin.sDiaDiem = model.sDiaDiem;
              dangTin.fMucLuong = model.fMucLuong;
              dangTin.dThoiGianHetHan = model.dThoiGianHetHan;
              dangTin.sMoTa = model.sMoTa;
              dangTin.dNgayTao = DateTime.Now;
              dangTin.sTrangThai = "Đang chờ duyệt";
              dangTin.FK_iMaTK = userId;*/
           
            bool result = await _dangTinService.CreatDangTin(model, userId);
            if (result)
            {
                TempData["Tittle"] = "Bài đăng của bạn đang chờ duyệt";
                TempData["SuccessMessage"] = "Đăng tin thành công!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Tittle"] = "Vui lòng điền đầy đủ thông tin";
                TempData["ErrorMessage"] = "Đăng tin thất bại!";
                //ModelState.AddModelError("", "Đăng tin không thành công!");
            }
            return View(model);
        }

        
        public async Task<IActionResult> Index(string trangthai = "Đang chờ duyệt")
        {
           
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baidangList = new List<BaiDangViewModel>();
            baidangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            /* var baiDangList=_context.BaiDangs
                 .Where(bd => bd.FK_iMaTK ==userId)
                 .ToList();
             var baidangList = new List<BaiDangViewModel>();
             baidangList=baiDangList.Select(bd => new BaiDangViewModel()
             {

                 sTieuDe = bd.sTieuDe,
                 sMoTa = bd.sMoTa,
                 sDiaDiem = bd.sDiaDiem,
                 fMucLuong = bd.fMucLuong ?? 0,
                 dThoiGianHetHan = bd.dThoiGianHetHan ?? DateTime.MinValue,
                 dNgayTao = bd.dNgayTao,
                 sTrangThai = bd.sTrangThai,

             }).ToList();*/

            return View(baidangList);
        }
        public async Task<IActionResult> IndexGS(string trangthai = "Đang chờ duyệt")
        {

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baidangList = new List<BaiDangViewModel>();
            baidangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            /* var baiDangList=_context.BaiDangs
                 .Where(bd => bd.FK_iMaTK ==userId)
                 .ToList();
             var baidangList = new List<BaiDangViewModel>();
             baidangList=baiDangList.Select(bd => new BaiDangViewModel()
             {

                 sTieuDe = bd.sTieuDe,
                 sMoTa = bd.sMoTa,
                 sDiaDiem = bd.sDiaDiem,
                 fMucLuong = bd.fMucLuong ?? 0,
                 dThoiGianHetHan = bd.dThoiGianHetHan ?? DateTime.MinValue,
                 dNgayTao = bd.dNgayTao,
                 sTrangThai = bd.sTrangThai,

             }).ToList();*/

            return View(baidangList);
        }
        [HttpPost]
        public async Task<IActionResult> SearchDB(string MonDay, string Diadiem, string ThoiGian, string TuKhoa,string nguoidang)
        { string trangthai = "Đang chờ duyệt";
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baiDangList = new List<BaiDangViewModel>();
            baiDangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            if (!string.IsNullOrEmpty(MonDay))
            {
                baiDangList = baiDangList.Where(bd => bd.sMonday.Contains(MonDay)).ToList();
            }
            if (!string.IsNullOrEmpty(nguoidang))
            {
                baiDangList = baiDangList.Where(bd => bd.Nguoitao.Contains(nguoidang)).ToList();
            }
            if (!string.IsNullOrEmpty(Diadiem))
            {
                baiDangList = baiDangList.Where(bd => bd.sDiaDiem.Contains(Diadiem)).ToList();
            }
            if (!string.IsNullOrEmpty(ThoiGian))
            {
                DateTime dateTime;
                if (DateTime.TryParse(ThoiGian, out dateTime))
                {
                    baiDangList = baiDangList.Where(bd => bd.dNgayTao.Date == dateTime.Date).ToList();
                }
            }
            if (!string.IsNullOrWhiteSpace(TuKhoa))
            {
                var keyword = RemoveDiacritics(TuKhoa).ToLower();
                baiDangList = baiDangList.Where(u => RemoveDiacritics(u.sMoTa).ToLower().Contains(keyword)).ToList();
            }
            return View("Index", baiDangList);
        }
        
        
      
        [HttpGet]
        public async Task<IActionResult> Get(int Primakey)
        {
            
            var dangTin = await _dangTinService.GetBaiDangById(Primakey);
            if (dangTin == null)
            {
                return NotFound();
            }
            
            return View(dangTin);
        }
        [HttpGet]
        public async Task<IActionResult> GetGS(int Primakey)
        {

            var dangTin = await _dangTinService.GetBaiDangByIdGS(Primakey);
            if (dangTin == null)
            {
                return NotFound();
            }

            return View(dangTin);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _dangTinService.DeleteDangTin(id);
            if (result)
            {

Views/Admin/CreateGDV.cshtml
@model WebApplication1.Models.ViewModels.ChonGoiViewModel
@using WebApplication1.Models

@{
    ViewData["Title"] = "Thêm gói dịch vụ";
    ViewData["UserRole"] = User.FindFirst("VaiTro")?.Value; // nếu bạn lưu vai trò bằng claim "VaiTro"
}

<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/StyleSidebar.css" />
    <link rel="stylesheet" href="~/css/StyleGDV.css" />
    <title>HUNO - Quản lý gói dịch vụ</title>

</head>
<body>
    <div class="container">
        @await Html.PartialAsync("_SidebarPartial", new
            {
                Controller = ViewContext.RouteData.Values["controller"]?.ToString(),
                Action = ViewContext.RouteData.Values["action"]?.ToString(),
                VaiTro = User.FindFirst("VaiTro")?.Value
            })
        <!-- Main Content -->
        <div class="main-content">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            <form asp-action="CreateGDV" method="post">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="mb-3">
                    <label asp-for="TenGoi" class="form-label">Tên gói</label>
                    <input asp-for="TenGoi" class="form-control" />
                    <span asp-validation-for="TenGoi" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="MoTa" class="form-label">Mô tả</label>
                    <textarea asp-for="MoTa" class="form-control"></textarea>
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Gia" class="form-label">Giá gói</label>
                    <input asp-for="Gia" class="form-control" />
                    <span asp-validation-for="Gia" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SoNgayHieuLuc" class="form-label">Số ngày hiệu lực</label>
                    <input asp-for="SoNgayHieuLuc" class="form-control" />
                    <span asp-validation-for="SoNgayHieuLuc" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success">Lưu</button>
                <a asp-action="QuanLyGoi" class="btn btn-secondary">Quay lại</a>
            </form>
        </div>
    </div>
</body>
</html>

Views/Admin/DSHS.cshtml
@model IEnumerable<WebApplication1.Models.ViewModels.HoSoViewModel>

@using WebApplication1.Models

@{
    ViewData["Title"] = "Ho So ";
    ViewData["UserRole"] = User.FindFirst("VaiTro")?.Value; // nếu bạn lưu vai trò bằng claim "VaiTro"
}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/styleDangTin.css" />
    <link rel="stylesheet" href="~/css/StyleSidebar.css" />
    <link rel="stylesheet" href="~/css/styleQlbd.css" />
    <link href="~/css/tb.css" rel="stylesheet" />
    <title>HUNO - Hồ sơ Tuyển Dụng</title>

</head>
<div class="container">
    @await Html.PartialAsync("_SidebarPartial", new
        {
            Controller = ViewContext.RouteData.Values["controller"]?.ToString(),
            Action = ViewContext.RouteData.Values["action"]?.ToString(),
            VaiTro = User.FindFirst("VaiTro")?.Value
        })
    <!-- Main Content -->
    <div class="main-content">
        <div class="notification-container">
            @await Html.PartialAsync("_Notification")
        </div>
        <!-- Content Area -->
        <div class="content" style="width:140%">

            <div class="search-container">

                <div class="section-title">
                    <form action="DSHS" method="get">
                        <a href="?trangthai=Đang chờ duyệt">Hồ Sơ chờ duyệt</a>
                        <a href="?trangthai=Đã duyệt">Hồ Sơ đã duyệt</a>
                    </form>
                </div>
                <form method="post" asp-action="SearchHSA">
                    <div class="search-row">

                        <div class="search-field">
                            <label class="search-label">Kỹ năng</label>
                            <select name="kynang" class="search-select">
                                <option value="" selected>Chọn</option>
                                <option>Giao tiếp</option>
                                <option>Giảng dạy</option>
                                <option>Ngoại ngữ</option>
                            </select>
                        </div>
                       
                    </div>

                    <div class="search-row">
                        <div class="search-field">
                            <label class="search-label">Tên ứng viên </label>
                            <input name="tieude" type="text" class="search-input" placeholder="Nhập từ khóa">
                        </div>
                        <button class="search-btn" type="submit">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M21 21L16.65 16.65M19 11C19 15.4183 15.4183 19 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                            Tìm
                        </button>
                    </div>
                </form>
            </div>

            <!-- Results section -->
            <div class="results-container">
                <table>
                    <thead>
                        <tr>
                            <th>Ứng viên</th>
                            <th>Tiêu đề</th>
                            <th>Kinh nghiệm</th>
                            <th>Bằng cấp</th>
                            <th>Kỹ năng</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>@item.HoTen</td>
                                <td>@item.sTieuDe</td>
                                <td class="ellipsis">@item.sKinhNghiem</td>
                                <td>@item.sBangCap</td>
                                <td>@item.sTrangThai</td>
                                <td class="action-cell">
                                    <form asp-action="GetHS" method="get">
                                        <button type="submit" class="action-btn" name="Primakey" value="@item.iMaHS">
                                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M15.0007 12C15.0007 13.6569 13.6576 15 12.0007 15C10.3439 15 9.00073 13.6569 9.00073 12C9.00073 10.3431 10.3439 9 12.0007 9C13.6576 9 15.0007 10.3431 15.0007 12Z" stroke="#8b3dff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12.0012 5C7.52354 5 3.73326 7.94288 2.45898 12C3.73324 16.0571 7.52354 19 12.0012 19C16.4788 19 20.2691 16.0571 21.5434 12C20.2691 7.94291 16.4788 5 12.0012 5Z" stroke="#8b3dff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                                        </button>
                                    </form>
                                    <form asp-action="DeleteHS" method="get">
                                        <button class="action-btn" type="submit" name="Id" value="@item.iMaHS">
                                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M3 6H5H21" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                                <path d="M8 6V4C8 3.46957 8.21071 2.96086 8.58579 2.58579C8.96086 2.21071 9.46957 2 10 2H14C14.5304 2 15.0391 2.21071 15.4142 2.58579C15.7893 2.96086 16 3.46957 16 4V6M19 6V20C19 20.5304 18.7893 21.0391 18.4142 21.4142C18.0391 21.7893 17.5304 22 17 22H7C6.46957 22 5.96086 21.7893 5.58579 21.4142C5.21071 21.0391 5 20.5304 5 20V6H19Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                            </svg>
                                        </button>
                                    </form>
                                    @if (item.sTrangThai != "Đã duyệt")
                                    {
                                        <form asp-action="PheDuyetHS" method="get">
                                            <button class="action-btn" type="submit" name="pd" value="@item.iMaHS">
                                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M2 12C2 7.28595 2 4.92893 3.46447 3.46447C4.92893 2 7.28595 2 12 2C16.714 2 19.0711 2 20.5355 3.46447C22 4.92893 22 7.28595 22 12C22 16.714 22 19.0711 20.5355 20.5355C19.0711 22 16.714 22 12 22C7.28595 22 4.92893 22 3.46447 20.5355C2 19.0711 2 16.714 2 12Z" stroke="#8b3dff" stroke-width="1.5"></path> <path d="M8.5 12.5L10.5 14.5L15.5 9.5" stroke="#8b3dff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                                            </button>
                                        </form>
                                    }
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    // Tab switching functionality
    const tabs = document.querySelectorAll('.tab');
    tabs.forEach(tab => {
      tab.addEventListener('click', () => {
        tabs.forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
      });
    });



    // Search button functionality
    const searchBtn = document.querySelector('.search-btn');
    searchBtn.addEventListener('click', () => {
      // In a real implementation, you would perform search here
      alert('Search functionality would be implemented here');
    });

    // Export button functionality
    const exportBtn = document.querySelector('.export-btn');
    exportBtn.addEventListener('click', () => {
      // In a real implementation, you would export data here
      alert('Export functionality would be implemented here');
    });

    // Row action buttons
    const actionBtns = document.querySelectorAll('.action-btn');
    actionBtns.forEach(btn => {
      btn.addEventListener('click', (e) => {
        const action = e.currentTarget.querySelector('svg').innerHTML.includes('plus') ? 'view' : 'delete';
        const row = e.currentTarget.closest('tr');
        const position = row.cells[0].textContent;

        if (action === 'view') {
          alert(`Viewing details for ${position}`);
        } else {
          if (confirm(`Are you sure you want to delete the job posting for ${position}?`)) {
            alert(`Deleted job posting for ${position}`);
          }
        }
      });
    });
</script>
</html>

Views/Admin/QuanLyGD.cshtml
@model List< WebApplication1.Models.ViewModels.LichSuTTViewModel>
@using WebApplication1.Models

@{
    ViewData["Title"] = "Quan ly Giao dich";
    ViewData["UserRole"] = User.FindFirst("VaiTro")?.Value; // nếu bạn lưu vai trò bằng claim "VaiTro"
}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/StyleSidebar.css" />
    <link rel="stylesheet" href="~/css/styleQlbd.css" />
    <link rel="stylesheet" href="~/css/styleDangTin.css" />
    <link rel="stylesheet" href="~/css/StyleDH.css" />
    <title>HUNO - Quản lý giao dịch</title>
    
        <style>
        .duyet-btn {
            background-color: #a782f3;
            color: white;
            border: none;
            padding: 4px 10px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: 500;
            cursor: pointer;
            display: inline-flex;
            align-items: center;
        }
        </style>
</head>
<body>
    <div class="container">
        @await Html.PartialAsync("_SidebarPartial", new
            {
                Controller = ViewContext.RouteData.Values["controller"]?.ToString(),
                Action = ViewContext.RouteData.Values["action"]?.ToString(),
                VaiTro = User.FindFirst("VaiTro")?.Value
            })
        <!-- Main Content -->
        <div class="main-content">
            <div class="content" style="width:140%">

                <div class="search-container">

                    <div class="section-title">
                        <form asp-controller="ThanhToan" asp-action="QuanLyGD" method="get">
                            <a href="@Url.Action("QuanLyGD", new { trangthaiGD = "Chờ duyệt" })">Giao dịch chờ duyệt</a>
                            <a href="@Url.Action("QuanLyGD", new { trangthaiGD = "Đã duyệt" })">Giao dịch đã duyệt</a>
                        </form>
                    </div>

                </div>

                @if (Model.Any())
                {
                    <div class="results-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Người dùng</th>
                                    <th>Tiêu đề bài đăng</th>
                                    <th>Ngày đăng</th>
                                    <th>Tên gói</th>
                                    <th>Số tiền</th>
                                    <th>Ngày thanh toán</th>
                                    <th>Ưu tiên đến</th>
                                    @if (Model.Any(item => item.TrangThaiGD == "Chờ duyệt"))
                                    {
                                        <th>Thao tác</th>
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.TenNguoiDung</td>
                                        <td>@item.TieuDeBaiDang</td>
                                        <td>@item.NgayDang.ToString("dd/MM/yyyy")</td>
                                        <td>@item.TenGoi</td>
                                        <td>@item.SoTien</td>
                                        <td>@item.NgayThanhToan.ToString("dd/MM/yyyy")</td>
                                        @if (item.TrangThaiGD == "Đã duyệt")
                                        {
                                        <td>@item.DayUuTienDen?.ToString("dd/MM/yyyy")</td>
                                        }
                                        @if (item.TrangThaiGD == "Chờ duyệt")
                                        {
                                            <td>
                                                <form asp-action="Duyet" method="post">
                                                    <input type="hidden" name="id" value="@item.Id" />
                                                    <button type="submit" class="duyet-btn">Duyệt</button>
                                                </form>
                                            </td>
                                        }
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <p>Chưa có giao dịch nào.</p>
                }
            </div>
        </div>
</body>
</html>
<script>
    // Tab switching functionality
    const tabs = document.querySelectorAll('.tab');
    tabs.forEach(tab => {
      tab.addEventListener('click', () => {
        tabs.forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
      });
    });
</script>