Controllers/BangTinController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using WebApplication1.Models.Entities;
using WebApplication1.Models.ViewModels;
using WebApplication1.Repositories;
using WebApplication1.Services;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Security.Claims;


namespace WebApplication1.Controllers
{
    public class BangTinController : Controller
    {
        private readonly IBangTinService _bangTinService;
        private readonly IBangTinRepository _bangTinRepository;
        private readonly UserManager<TaiKhoan> _userManager;
        private readonly IUngTuyenService _IUngTuyenService;
        private readonly IAccountRepository _taiKhoanRepo;

        public BangTinController(IBangTinService bangTinService, IBangTinRepository bangTinRepository, UserManager<TaiKhoan> userManager,IUngTuyenService ungTuyenService, IAccountRepository taiKhoanRepo)
        {
            _bangTinService = bangTinService;
            _bangTinRepository = bangTinRepository;
            _userManager = userManager;
            _IUngTuyenService = ungTuyenService;
            _taiKhoanRepo = taiKhoanRepo;
        }
        public IActionResult Index()
        { var page = new BaiDangPageViewModel();
            var userId = _userManager.GetUserId(User); // sẽ là null nếu chưa đăng nhập
            page = _bangTinService.GetAllBaiDangsAsync(userId).Result;
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }
        [HttpPost]
        public async Task<IActionResult> UngTuyen(int baiDangId)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var taiKhoan = await _taiKhoanRepo.GetTaiKhoanByIdAsync(userId);

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (taiKhoan == null)
                return Unauthorized();

            if (taiKhoan.VaiTro != "giasu")
                return Forbid(); // 🚫 Không cho phép nếu không phải Gia Sư

            try
            {
                TempData["Tittle"] = "Hồ sơ của bạn đang chờ chấp nhận";
                TempData["SuccessMessage"] = "Ứng tuyển thành công!";
                await _IUngTuyenService.UngTuyenAsync(userId, baiDangId);
                return RedirectToAction("Index");
            }
            catch (InvalidOperationException ex)
            {
                // Nếu gia sư đã ứng tuyển vào bài đăng
                TempData["Tittle"] = "Bạn đã ứng tuyển bài đăng này";
                TempData["ErrorMessage"] = "Ứng tuyển thất bại!";
                return View("Index"); // Quay lại trang Index với thông báo lỗi
            }
        }
      




    }
}

Controllers/SPDVController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class SPDVController : Controller
    {
        private readonly ILogger<SPDVController> _logger;
        private readonly ApplicationDbContext _context;

        public SPDVController(ILogger<SPDVController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var goiDichVus = _context.GoiDichVus.ToList(); // hoặc dùng service gọi từ DB
            var model = new GoiViewModel
            {
                GoiDichVus = goiDichVus,
                BaiDangId = 1 // hoặc lấy ID hợp lệ tương ứng
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/baiDangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Models.Entities;
using WebApplication1.Repositories;
using WebApplication1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Globalization;
using System.Text;

namespace WebApplication1.Controllers
{
    public class baiDangController : Controller
    {
        private readonly ILogger<baiDangController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly UserManager<TaiKhoan> _userManager;
        private readonly SignInManager<TaiKhoan> _signInManager;
        private readonly IDangTinService _dangTinService;
        private readonly IDangTinRepository _dangTinRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly IUngTuyenService _IUngTuyenService;
        private readonly ICustomEmailSender _emailSender;
        private readonly IUngTuyenRepository _ungTuyenRepo;

        public baiDangController(
            ILogger<baiDangController> logger,
            IWebHostEnvironment webHostEnvironment,
            ApplicationDbContext context,
            IConfiguration configuration,
            UserManager<TaiKhoan> userManager,
            SignInManager<TaiKhoan> signInManager,
            IDangTinService dangTinService,
            IAccountRepository accountRepository,
            IUngTuyenService IUngTuyenService,
            IDangTinRepository dangTinRepository,
            ICustomEmailSender emailSender,
            IUngTuyenRepository ungTuyenRepo
            )
        {
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _configuration = configuration;
            _userManager = userManager;
            _signInManager = signInManager;
            _dangTinService = dangTinService;
            _dangTinRepository = dangTinRepository;
            _accountRepository = accountRepository;
            _IUngTuyenService = IUngTuyenService;
            _emailSender = emailSender;
            _ungTuyenRepo = ungTuyenRepo;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult DangTin()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> DangTin(DangTinViewModel model)
        {
           
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            _logger.LogInformation("DangTin action called with model: {@Model}", model);


            if (string.IsNullOrEmpty(model.sTieuDe) || string.IsNullOrEmpty(model.sDiaDiem) || model.fMucLuong <= 0 || string.IsNullOrEmpty(model.sMoTa) || string.IsNullOrEmpty(model.sYCau) || string.IsNullOrEmpty(model.sBangCap) || string.IsNullOrEmpty(model.sGioiTinh) || string.IsNullOrEmpty(model.sKinhNghiem) || string.IsNullOrEmpty(model.sMonday) || string.IsNullOrEmpty(model.sTuoi))
            {
                ModelState.AddModelError("", "Vui lòng điền đầy đủ thông tin!");
                return View(model);
            }

            //var dangTin = new BaiDang();

          //  bool isExist = await _dangTinService.DangTinExistsByTitleAsync(model.sTieuDe);
            //if (isExist)
           // {
            //    ModelState.AddModelError("", "Tiêu đề đã tồn tại!");
           //     return View(model);
           // }
            /*  dangTin.sMonday = model.sMonday;
              dangTin.sYCau = model.sYCau;
              dangTin.sGioiTinh = model.sGioiTinh;
              dangTin.sTuoi = model.sTuoi;
              dangTin.sKinhNghiem = model.sKinhNghiem;
              dangTin.sBangCap = model.sBangCap;
              dangTin.sTieuDe = model.sTieuDe;
              dangTin.sDiaDiem = model.sDiaDiem;
              dangTin.fMucLuong = model.fMucLuong;
              dangTin.dThoiGianHetHan = model.dThoiGianHetHan;
              dangTin.sMoTa = model.sMoTa;
              dangTin.dNgayTao = DateTime.Now;
              dangTin.sTrangThai = "Đang chờ duyệt";
              dangTin.FK_iMaTK = userId;*/
           
            bool result = await _dangTinService.CreatDangTin(model, userId);
            if (result)
            {
                TempData["Tittle"] = "Bài đăng của bạn đang chờ duyệt";
                TempData["SuccessMessage"] = "Đăng tin thành công!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Tittle"] = "Vui lòng điền đầy đủ thông tin";
                TempData["ErrorMessage"] = "Đăng tin thất bại!";
                //ModelState.AddModelError("", "Đăng tin không thành công!");
            }
            return View(model);
        }

        
        public async Task<IActionResult> Index(string trangthai = "Đang chờ duyệt")
        {
           
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baidangList = new List<BaiDangViewModel>();
            baidangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            /* var baiDangList=_context.BaiDangs
                 .Where(bd => bd.FK_iMaTK ==userId)
                 .ToList();
             var baidangList = new List<BaiDangViewModel>();
             baidangList=baiDangList.Select(bd => new BaiDangViewModel()
             {

                 sTieuDe = bd.sTieuDe,
                 sMoTa = bd.sMoTa,
                 sDiaDiem = bd.sDiaDiem,
                 fMucLuong = bd.fMucLuong ?? 0,
                 dThoiGianHetHan = bd.dThoiGianHetHan ?? DateTime.MinValue,
                 dNgayTao = bd.dNgayTao,
                 sTrangThai = bd.sTrangThai,

             }).ToList();*/

            return View(baidangList);
        }
        public async Task<IActionResult> IndexGS(string trangthai = "Đang chờ duyệt")
        {

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baidangList = new List<BaiDangViewModel>();
            baidangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            /* var baiDangList=_context.BaiDangs
                 .Where(bd => bd.FK_iMaTK ==userId)
                 .ToList();
             var baidangList = new List<BaiDangViewModel>();
             baidangList=baiDangList.Select(bd => new BaiDangViewModel()
             {

                 sTieuDe = bd.sTieuDe,
                 sMoTa = bd.sMoTa,
                 sDiaDiem = bd.sDiaDiem,
                 fMucLuong = bd.fMucLuong ?? 0,
                 dThoiGianHetHan = bd.dThoiGianHetHan ?? DateTime.MinValue,
                 dNgayTao = bd.dNgayTao,
                 sTrangThai = bd.sTrangThai,

             }).ToList();*/

            return View(baidangList);
        }
        [HttpPost]
        public async Task<IActionResult> SearchDB(string MonDay, string Diadiem, string ThoiGian, string TuKhoa,string nguoidang)
        { string trangthai = "Đang chờ duyệt";
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var baiDangList = new List<BaiDangViewModel>();
            baiDangList = await _dangTinService.GetAllBaiDangByTaiKhoanId(userId, trangthai);
            if (!string.IsNullOrEmpty(MonDay))
            {
                baiDangList = baiDangList.Where(bd => bd.sMonday.Contains(MonDay)).ToList();
            }
            if (!string.IsNullOrEmpty(nguoidang))
            {
                baiDangList = baiDangList.Where(bd => bd.Nguoitao.Contains(nguoidang)).ToList();
            }
            if (!string.IsNullOrEmpty(Diadiem))
            {
                baiDangList = baiDangList.Where(bd => bd.sDiaDiem.Contains(Diadiem)).ToList();
            }
            if (!string.IsNullOrEmpty(ThoiGian))
            {
                DateTime dateTime;
                if (DateTime.TryParse(ThoiGian, out dateTime))
                {
                    baiDangList = baiDangList.Where(bd => bd.dNgayTao.Date == dateTime.Date).ToList();
                }
            }
            if (!string.IsNullOrWhiteSpace(TuKhoa))
            {
                var keyword = RemoveDiacritics(TuKhoa).ToLower();
                baiDangList = baiDangList.Where(u => RemoveDiacritics(u.sMoTa).ToLower().Contains(keyword)).ToList();
            }
            return View("Index", baiDangList);
        }
        
        
      
        [HttpGet]
        public async Task<IActionResult> Get(int Primakey)
        {
            
            var dangTin = await _dangTinService.GetBaiDangById(Primakey);
            if (dangTin == null)
            {
                return NotFound();
            }
            
            return View(dangTin);
        }
        [HttpGet]
        public async Task<IActionResult> GetGS(int Primakey)
        {

            var dangTin = await _dangTinService.GetBaiDangByIdGS(Primakey);
            if (dangTin == null)
            {
                return NotFound();
            }

            return View(dangTin);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _dangTinService.DeleteDangTin(id);
            if (result)
            {

Views/SPDV/Index.cshtml
@model WebApplication1.Models.ViewModels.GoiViewModel

@using WebApplication1.Models

@{
    ViewData["Title"] = "San Pham Dich Vu";
}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/styleNav.css" />
    <link rel="stylesheet" href="~/css/StyleSPDV.css" />
    <title>BOWO - Nền tảng Tuyển Dụng</title>

</head>
<body>
    <div class="main-content">
        <section class="hero-section">
            <h1>ĐĂNG TIN TUYỂN DỤNG</h1>
            <p>Cập nhật và hiển thị tin đăng ở vị trí nổi bật</p>
            <a asp-controller="BangTin" asp-action="Index" class="action-btn">Khám phá ngay</a>
        </section>

        <section class="features-grid">
            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="Calendar and clock illustration">
                </div>
                <h3>Hiển thị ngay lập tức trên trang BOWO</h3>
                <p>Tin tuyển dụng sẽ được hiển thị ngay lập tức tại bowo.vn trong 30 ngày.</p>
            </div>

            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="Mobile search illustration">
                </div>
                <h3>Linh hoạt và tiết kiệm</h3>
                <p>Nhiều gói dịch vụ đăng tuyển đã đang giúp Nhà tuyển dụng tiết kiệm đến 58% chi phí với quyền lợi sử dụng linh hoạt trong thời hạn 1 năm.</p>
            </div>

            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="Content management illustration">
                </div>
                <h3>Tùy chỉnh nội dung trong suốt thời gian đăng tuyển</h3>
                <p>Nhà tuyển dụng có thể dễ dàng cập nhật và thay đổi thông tin trong suốt thời gian đăng tuyển.</p>
            </div>

            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="HR management illustration">
                </div>
                <h3>Thêm lợi ích, không phụ thu</h3>
                <p>Vị trí đăng tuyển sẽ được hiển thị đồng thời tại các trang liên kết thuộc hệ sinh thái BOWO, hoàn toàn miễn phí.</p>
            </div>

            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="Job description template illustration">
                </div>
                <h3>Thư viện mẫu mô tả công việc gợi ý theo từng chức danh</h3>
                <p>Tham khảo bản mô tả công việc chuyên nghiệp từ thư viện theo từng chức danh đa dạng và luôn cập nhật.</p>
            </div>

            <div class="feature-card">
                <div class="feature-img">
                    <img src="/api/placeholder/300/200" alt="HR Central illustration">
                </div>
                <h3>HR Central - trang quản lý nguồn ứng viên trực tuyến</h3>
                <p>Toàn bộ hồ sơ ứng tuyển nhanh chóng được phân loại, quản lý chuyên nghiệp trong HRCentral giúp tiết kiệm X2 thời gian sàng lọc, theo dõi quá trình ứng tuyển.</p>
            </div>
        </section>

        <section class="pricing-section">
            <h2>SẴN SÀNG XÂY DỰNG ĐỘI NGŨ NHÂN TÀI CHO DOANH NGHIỆP</h2>
            <p class="pricing-disclaimer">*Lưu ý: Giá chưa bao gồm phí VAT</p>

            <div class="pricing-grid">
                @foreach (var goi in Model.GoiDichVus)
                {
                    <form asp-controller="baiDang" asp-action="Index" asp-route-goiId="@goi.Id" asp-route-baiDangId="@Model.BaiDangId" class="goi-form">
                        <div class="pricing-card">
                            <button type="submit" class="goi-button">
                                <h3>@goi.TenGoi</h3>
                            </button>
                            <div class="price">@goi.Gia</div>
                            <div class="pricing-features">
                                @goi.MoTa
                            </div>
                        </div>
                    </form>
                }
        </section>

        <section class="templates-section">
            <h2>MẪU ĐĂNG TUYỂN</h2>
            <div class="templates-grid">
                <div class="template-card">
                    <img src="/api/placeholder/250/350" alt="Job posting template 1" class="template-img">
                </div>
                <div class="template-card">
                    <img src="/api/placeholder/250/350" alt="Job posting template 2" class="template-img">
                </div>
                <div class="template-card">
                    <img src="/api/placeholder/250/350" alt="Job posting template 3" class="template-img">
                </div>
                <div class="template-card">
                    <img src="/api/placeholder/250/350" alt="Job posting template 4" class="template-img">
                </div>
            </div>
        </section>
    </div>
</body>
<footer>
    <div class="footer-grid">
        <div class="footer-section">
            <h4>Về BOWO</h4>
            <ul class="footer-links">
                <li><a href="#">Giới thiệu</a></li>
                <li><a href="#">Tuyển dụng</a></li>
                <li><a href="#">Liên hệ</a></li>
                <li><a href="#">Chính sách bảo mật</a></li>
            </ul>
        </div>

        <div class="footer-section">
            <h4>Dành cho Nhà Tuyển Dụng</h4>
            <ul class="footer-links">
                <li><a href="#">Đăng tin tuyển dụng</a></li>
                <li><a href="#">Tìm hồ sơ ứng viên</a></li>
                <li><a href="#">Báo giá dịch vụ</a></li>
                <li><a href="#">Quảng cáo tuyển dụng</a></li>
            </ul>
        </div>

        <div class="footer-section">
            <h4>Dành cho Ứng Viên</h4>
            <ul class="footer-links">
                <li><a href="#">Tìm việc làm</a></li>
                <li><a href="#">Tạo CV online</a></li>
                <li><a href="#">Cẩm nang nghề nghiệp</a></li>
                <li><a href="#">Tư vấn nghề nghiệp</a></li>
            </ul>
        </div>

        <div class="footer-section">
            <h4>Kết nối</h4>
            <ul class="footer-links">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">LinkedIn</a></li>
                <li><a href="#">YouTube</a></li>
                <li><a href="#">Zalo</a></li>
            </ul>
        </div>
    </div>

    <div class="copyright">
        © 2025 BOWO. Tất cả quyền được bảo lưu.
    </div>
</footer>
</html>
<script>
    // JavaScript for interactive functionality
    document.addEventListener('DOMContentLoaded', function() {
        // Tab switching functionality
        const tabLinks = document.querySelectorAll('.tabs a');

        tabLinks.forEach(function(tab) {
            tab.addEventListener('click', function(e) {
                e.preventDefault();

                // Remove active class from all tabs
                tabLinks.forEach(t => t.classList.remove('active'));

                // Add active class to clicked tab
                this.classList.add('active');

                // Here you would typically update content based on tab
                // For example: showContent(this.getAttribute('data-tab'));
            });
        });

        // Pricing card hover effects
        const pricingCards = document.querySelectorAll('.pricing-card');

        pricingCards.forEach(function(card) {
            card.addEventListener('mouseenter', function() {
                this.classList.add('hover');
            });

            card.addEventListener('mouseleave', function() {
                this.classList.remove('hover');
            });
        });

        // Mobile menu toggle (if needed)
        const menuToggle = document.createElement('button');
        menuToggle.className = 'menu-toggle';
        menuToggle.innerHTML = '<span></span><span></span><span></span>';
        document.querySelector('.header-container').appendChild(menuToggle);

        menuToggle.addEventListener('click', function() {
            document.querySelector('.main-nav').classList.toggle('active');
        });

        // Smooth scroll to sections
        const ctaButton = document.querySelector('.cta-button');

        ctaButton.addEventListener('click', function(e) {
            e.preventDefault();
            document.querySelector('.pricing').scrollIntoView({
                behavior: 'smooth'
            });
        });

        // Template gallery functionality
        const templates = document.querySelectorAll('.template');

        templates.forEach(function(temp, index) {
            temp.addEventListener('click', function() {
                // Show template preview or details
                alert('Đang xem chi tiết mẫu đăng tuyển ' + (index + 1));
                // In a real implementation, you might open a modal with template details
            });
        });
    });

    // Function to handle form submission for job posting
    function submitJobPosting(formData) {
        // This would be implemented to send data to server
        console.log('Dữ liệu đăng tin:', formData);
        // Example AJAX call that would be implemented
        /*
        fetch('https://api.bowo.vn/job-posting', {
            method: 'POST',
            body: JSON.stringify(formData),
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => response.json())
        .then(data => {
            if(data.success) {
                alert('Đăng tin thành công!');
            } else {
                alert('Có lỗi xảy ra: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Có lỗi khi gửi dữ liệu');
        });
        */
    }

    // Function to handle package selection
    function selectPackage(packageId) {
        const packages = {
            'regular': {
                name: 'REGULAR POSTING',
                price: '1.750M',
                features: ['Đăng tin trong 30 ngày', 'Hiển thị đồng thời trên mobile app & trang web']
            },
            'extra': {
                name: 'EXTRA PACKAGE',
                price: '2.880M',
                features: ['Đăng tin trong 30 ngày', 'Tiêu đề in Đậm trong 30 ngày']
            },
            // Add other packages here
        };

        const selectedPackage = packages[packageId];
        if(selectedPackage) {
            console.log('Đã chọn gói:', selectedPackage.name);
            // In a real implementation, you would update UI or redirect to checkout
            return selectedPackage;
        }

        return null;
    }

    // Function to toggle dark/light mode (could be implemented)
    function toggleTheme() {
        const body = document.body;
        body.classList.toggle('dark-mode');

        // Save preference to localStorage
        const isDarkMode = body.classList.contains('dark-mode');
        localStorage.setItem('darkMode', isDarkMode);

        // Update theme stylesheet
        const themeStyle = document.getElementById('theme-style');
        themeStyle.href = isDarkMode ? 'dark-styles.css' : 'styles.css';
    }

    // Function to handle search functionality
    function searchJobs(query) {
        console.log('Tìm kiếm:', query);
        // In a real implementation, this would fetch results from API
        // and update the page content
    }
</script>